---
- name: Deploy Apache on Debian-based hosts like Ubuntu
  apt:
    name: apache2
    state: present
  when: ansible_os_family == 'Debian'
 
- name: Start Apache on Debian-based hosts like Ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'
