---
- hosts: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: Ensure the chrony NTP daemon is installed
      apt:
        name: chrony
        state: present


    - name: Ensure that the chrony NTP daemon is running
      service:
        name: chronyd
        state: started
        enabled: yes

  vars_files:
    - vars/linuxsecrets.yml
